### ISSUE TITLE
Security threat

### ISSUE THREAD

**Issue by Asim-Shah-2004** [atupatu/backend-iskimaaka#1]
The .env file is exposed with API KEY which can lean to potential misuse 

![Screenshot_20241105_233029_Chrome](https://github.com/user-attachments/assets/e672d192-d2e2-4858-8b1a-5573724f99f3)

**Comment by atupatu** [comment]
xD wo expired hai shayad

**Comment by Asim-Shah-2004** [comment]
Still I think you should add for good pratice
